module.exports = [
  "chair",
  "car",
  "computer",
  "keyboard",
  "mouse",
  "bike",
  "ball",
  "gloves",
  "pants",
  "shirt",
  "table",
  "shoes",
  "hat",
  "towels",
  "soap",
  "tuna",
  "chicken",
  "fish",
  "cheese",
  "bacon",
  "pizza",
  "salad",
  "sausages",
  "chips",
  "books",
  "movies",
  "music",
  "games",
  "electronics",
  "computers",
  "home",
  "garden",
  "tools",
  "grocery",
  "health",
  "beauty",
  "toys",
  "kids",
  "baby",
  "clothing",
  "shoes",
  "jewelery",
  "sports",
  "outdoors",
  "bread",
  "apple butter",
  "apple sauce",
  "baked potato",
  "barbecue",
  "bear claw",
  "beef manhattan",
  "bookbinder soup",
  "breakfast burrito",
  "brunswick stew",
  "buffalo burger",
  "buffalo wing",
  "bull roast",
  "burnt ends",
  "butter cookie",
  "cajun cuisine",
  "carolina style",
  "celery victor",
  "cheese dog",
  "cheese fries",
  "cheese steak",
  "chicken divan",
  "chicken fingers",
  "chicken french",
  "chicken nugget",
  "chicken parmigiana",
  "chicken sandwich",
  "chili dog",
  "chimichanga",
  "dark chocolate",
  "milk chocolate",
  "white chocolate",
  "choco pie",
  "chowder",
  "city chicken",
  "clam cake",
  "clam chowder",
  "coleslaw",
  "cordon bleu",
  "corn chowder",
  "corn dog",
  "corn flakes",
  "corn relish",
  "corned beef",
  "cowboy beans",
  "crab cake",
  "creamed corn",
  "deviled crab",
  "deviled egg",
  "domesticated turkey",
  "doughnut",
  "drunken chicken",
  "eggo",
  "eggs benedict",
  "eggs neptune",
  "energy bar",
  "turducken",
  "fajita",
  "fortune cookie",
  "french dip",
  "fried chicken",
  "fried fish",
  "fry sauce",
  "frybread",
  "garden salad",
  "goulash",
  "grits",
  "hamburger",
  "hangtown fry",
  "haystack",
  "hog fry",
  "home fries",
  "hot chicken",
  "italian beef",
  "italian dressing",
  "jerky",
  "juba",
  "lobster newberg",
  "lobster roll",
  "london broil",
  "lorna doone",
  "macaroni salad",
  "maraca pie",
  "mashed potato",
  "mashed pumpkin",
  "meatcake",
  "meatloaf",
  "milk toast",
  "milkshake",
  "mission burrito",
  "mozzarella sticks",
  "muffuletta",
  "mulligan stew",
  "onion ring",
  "oreo",
  "oysters rockefeller",
  "pancakes",
  "pasta salad",
  "pastrami",
  "patty",
  "peanut butter",
  "pemmican",
  "pepperoni",
  "pickled cucumber",
  "pizza strips",
  "ploye",
  "popcorn",
  "popover",
  "poppyseed muffin",
  "potato salad",
  "potato skins",
  "potato wedges",
  "protein bar",
  "pulled pork",
  "pumpkin pie",
  "rabbit pie",
  "ranch dressing",
  "reuben sandwich",
  "ribs",
  "rolled oyster",
  "russian dressing",
  "salisbury steak",
  "sandwich",
  "sausage gravy",
  "scrapple",
  "seafood cocktail",
  "sloppy joe",
  "smelt",
  "soul food",
  "sour cream",
  "steak",
  "steak sandwich",
  "steak sauce",
  "steamed clams",
  "stuffed ham",
  "stuffed peppers",
  "stuffed zucchini",
  "swiss steak",
  "toaster strudel",
  "tomato compote",
  "tuna casserole",
  "turducken",
  "thanksgiving turkey",
  "vichyssoise",
  "waffle",
  "sushi"
];
